# Generated by Django 4.2.10 on 2025-02-17 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_following_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
